#!/bin/bash

USR='devops'

for host in `cat remotehosts`
do
   echo "################################################"
   echo "Connecting to $host"
   scp websetup.sh $USR@$host:/tmp/
   echo "Exeucuting the Script on $host"
   ssh $USR@$host sudo /tmp/websetup.sh
   ssh $USR@$host sudo rm-rf /tmp/websetup.sh
   echo "################################################"
echo
done